export const FormErrorTypes = {
  UNIQUE: 'unique',
  ALPHA: 'alpha',
  URL: 'url',
  MAX_LENGTH: 'maxlength',
  MIN_LENGTH: 'minlength',
  MIN_NUMBER: 'minNumber',
  MAX_NUMBER: 'maxNumber',
  LESS_THAN_MAIL_DATE: 'lessThanMailDate',
  LESS_THAN_PRINT_DATE: 'lessThanPrintDate',
  LESS_THAN_DUE_DATE: 'lessThanDueDate',
  MISMATCH_PASSWORD: 'misMatchPassword',
  PASSWORD_POLICY: 'passwordPolicy',
  SAME_AS_OLD_PASSWORD: 'sameAsOldPassword',
  INVALID_PHONE: 'inValidPhone',
  INVALID: 'inValid',
  REQUIRED: 'required',
  WRONG_PAGE_COUNT: 'wrongPageCount',
  LESS_THAN_FROM_PAGE: 'lessThanFromPage',
  NOT_VALID_FOR_SELECTED_PAGES: 'notValidforSelectedPages',
  ALREADY_SELECTED: 'alreadySelected',
};
